# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfdry" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "e06d517cbbf15abf972ef1364ecea06a4afc8fb757e0d96d49ac02a08c380333"
      url "https://github.com/mchv/tfdry/releases/download/v#{version}/tfdry_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3bb92fa6b421fa48c56a67ebb2bf760a27cc34d075f1b5161c9d1bcd98bccb01"
      url "https://github.com/mchv/tfdry/releases/download/v#{version}/tfdry_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "07721db5374cb457f6133ad455fabfba5029e4c9bd7bf16e3e841d1f4b58f3d0"
      url "https://github.com/mchv/tfdry/releases/download/v#{version}/tfdry_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfdry"
  desc "Fast, focused Terraform linting — no terraform init, no state, no network."
  homepage "https://github.com/mchv/tfdry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfdry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfdry"]
    end
  end

  # No zap stanza required

end
