# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfdry" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "2b78c359384d424528497dab859ed485e404cce24dc0b9ba75c34a54dbb0a5de"
      url "https://github.com/mchv/tfdry/releases/download/v#{version}/tfdry_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d95840224cfe1469ee5d2b8aeab4798a41d57e9201e37f9e079e6ca1ee5beadd"
      url "https://github.com/mchv/tfdry/releases/download/v#{version}/tfdry_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5afdbd50cf51024322ab332d6e5e3419693753d5d99bfa6bfd62a0a582747a4"
      url "https://github.com/mchv/tfdry/releases/download/v#{version}/tfdry_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfdry"
  desc "Fast, focused Terraform linting — no terraform init, no state, no network."
  homepage "https://github.com/mchv/tfdry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfdry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfdry"]
    end
  end

  # No zap stanza required

end
